# Generated by Django 3.2.8 on 2021-12-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_product_count_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoritesProducts',
        ),
    ]
