# Generated by Django 3.2.8 on 2021-11-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_shopuser_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='avatar_url',
            field=models.URLField(),
        ),
    ]
