# Generated by Django 3.2.8 on 2021-11-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_shopuser_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='avatar_url',
        ),
    ]
