# Generated by Django 3.2.8 on 2021-11-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_remove_shopuser_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
